### PR TITLE
Add `.vscode/launch_template.json`

### PR DESCRIPTION
**Pull request by jgwhite**
Just a few debug profiles to get us started

### CODE REVIEW

**Comment by gregone** [comment]
thank you!

**Review by gregone — APPROVED** [review]

**Review by krantzinator — APPROVED** [review]
Wooooo 🎉 🙌🏻

**Comment by krantzinator** [comment]
@jgwhite Actually, idea on this -- should we name this `launch_template.json` or some such, so that we can alter our local launch.json with various things and have that in our local `gitignore` and not worry about overwriting all the time?

**Comment by jgwhite** [comment]
> @jgwhite Actually, idea on this -- should we name this `launch_template.json` or some such, so that we can alter our local launch.json with various things and have that in our local `gitignore` and not worry about overwriting all the time?

Great idea @krantzinator. I’ve applied this change.

**Pull request merged**
