### PR TITLE
Workspace scoped polling and project settings

### LINKED ISSUE #1665: Feature Request: Workspace-scoped project settings
**Is your feature request related to a problem? Please describe.**

For some reason, setting up the project settings on a workspace, applies them to _all the workspaces_.
This could either be a good thing (no need to do it manually), but also a bad thing (you can't have branch=workspace for a project).

**Describe the solution you'd like**
Ideally, one should be able to poll from git using different settings for each workspace. With this addition, it should be possible to have a GitOps repository where you store (divided in multiple branches) different configurations for Waypoint, so that Waypoint can poll them.

**Describe alternatives you've considered**
Creating a project for each environment

**Explain any additional use-cases**
- Different git target for different workspaces

**Additional context**

The view / settings are the same for each workspace, causing the git poll to be performed only on the `default` workspace and thus defeating the purpose of having workspaces in the first place.

Screenshot 2021-06-17 at 11 55 46

### PR DESCRIPTION
**Pull request by denysvitali**
Fixes #1665 

This PR heavily depends on #1821, therefore I'm waiting that to be merged to merge this one. The code might not be perfect, yet, but I would like to have comments / thoughts on that already since this might be the wrong way of implementing the fix for the above mentioned issue #1665 .

In any case, we're trying this feature out on our environment and it seems to work pretty well, together with #1821 the use of monorepos for Waypoint is finally working well 🚀

---

### `scoped_settings`

Thanks to `scoped_settings` it is now possible to specify a different poll behavior based on the workspace. Following is an example of the new syntax:

```hcl
runner {
    enabled = "true"
    scoped_settings {
        workspace "develop" {
            data_source "git" {
                url  = "https://github.com/hashicorp/waypoint-examples.git"
                path = "docker/node-js"
                ref = "develop"
            }
        }

        workspace "staging" {
            data_source "git" {
                url  = "https://github.com/hashicorp/waypoint-examples.git"
                path = "docker/node-js"
                ref = "staging"
            }
        }

        workspace "prod" {
            data_source "git" {
                url  = "https://github.com/hashicorp/waypoint-examples.git"
                path = "docker/node-js"
                ref = "prod"
            }
        }
    }
}
```

### `waypoint project details`

This new command now shows details related to the project, so that one can check wheter scoped settings are applied for the specified workspace:

```
$ waypoint project detail project-1
            KEY           |                         VALUE
--------------------------+---------------------------------------------------------
  Name                    | project-1
  Data Source             | git
  Git Url                 | https://github.com/hashicorp/waypoint-examples.git
  Git Ref                 | develop
  Git Path                | docker/node-js
  Git Auth Type           | unknown
  default Scoped Settings | N/A
```

### CODE REVIEW

**Comment by denysvitali** [comment]
Ping @mitchellh and @briancain for a review :)

**Comment by denysvitali** [comment]
Okay, now that #1821 is merged, this PR can be reviewed / merged too :)

cc/ @mitchellh @evanphx @briancain

**Comment by evanphx** [comment]
Looking back at this (hi @denysvitali),

The team isn't convinced this is the right way to approach this problem still. Waypoint has added and changed a lot around workspaces since it was opened. Are you willing to have another look at what this does and what waypoint does and see if it's still missing functionality for you?

**Comment by briancain** [comment]
Hello @denysvitali! Thank you so much for your contribution here, we are sorry we didn't get you an answer on this pull request sooner than now.

Given our decision to integrate workspace scoped git poll settings for an upcoming feature ([see comment](https://github.com/hashicorp/waypoint/issues/1665#issuecomment-1145255547)), pipelines, we don't intend to support this pull request at the moment. Because of that, I'm going to go ahead and close this pull request since we aren't expecting you to rebase it to work with the pipelines feature.

Thank you again for this contribution, and all of your previous contributions and direct feedback as an early Waypoint user! We appreciate it and hope you are still enjoying using Waypoint ✨

**Pull request closed without merging**
