### PR TITLE
Bump the `ember-build-tests` resource class

### PR DESCRIPTION
**Pull request by gregone**
Fixes: https://github.com/hashicorp/waypoint/issues/2260

starting with `medium+`, we'll see if that works, otherwise we could go to `large` to be sure.

### CODE REVIEW

**Review by jgwhite — APPROVED** [review]

**Comment by jgwhite** [comment]
The process still uses all available memory 🤦‍♀️ but this should give us some headroom.

image

**Comment by gregone** [comment]
😭

**Comment by gregone** [comment]
@jgwhite setting `JOBS=1` actually brings the memory usage back down slightly under 5GB 🥲 
Screen Shot 2021-09-14 at 15 15 00

**Comment by jgwhite** [comment]
> @jgwhite setting `JOBS=1` actually brings the memory usage back down slightly under 5GB 🥲
> Screen Shot 2021-09-14 at 15 15 00

It also doesn’t seem increase the build time much. I guess Babel isn’t embarrassingly parallel.

**Pull request merged**
