### PR TITLE
Upgrade docker/docker

### LINKED ISSUE #1684: Bug: build never falls back to img
**Describe the bug**
Waypoint currently does not fall back to using `img` builds when docker is not present.

**Steps to Reproduce**
Install waypoint with docker, create a new project with github polling configured, and observe as the runner fails the build complaining about the docker socket.

This can also be observed by enabling trace logging and performing a normal `waypoint build` locally with docker disabled:

```
2021-06-21T23:44:35.371-0400 [DEBUG] waypoint.runner.app.example-nodejs-k8s.builder.waypoint: testing if Docker is available: job_id=01F8RX3Q6EM1HAH8J8SZ6K3S9V job_op=*gen.Job_Build @module=waypoint.runner.app.example-nodejs-k8s.build timestamp=2021-06-21T23:44:35.371-0400
2021-06-21T23:44:35.371-0400 [TRACE] waypoint.runner.app.example-nodejs-k8s.builder.waypoint: testing Docker client connection by calling ServerVersion: job_id=01F8RX3Q6EM1HAH8J8SZ6K3S9V job_op=*gen.Job_Build @module=waypoint.runner.app.example-nodejs-k8s.build.docker_fallback_check timestamp=2021-06-21T23:44:35.371-0400
2021-06-21T23:44:35.372-0400 [TRACE] waypoint.runner.app.example-nodejs-k8s.builder.waypoint: ServerVersion fallback check failed with non-connection error: job_id=01F8RX3Q6EM1HAH8J8SZ6K3S9V job_op=*gen.Job_Build @module=waypoint.runner.app.example-nodejs-k8s.build.docker_fallback_check err="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" timestamp=2021-06-21T23:44:35.372-0400
2021-06-21T23:44:35.373-0400 [WARN]  waypoint.runner.app.example-nodejs-k8s.builder.waypoint: error during check if we should use Docker fallback: job_id=01F8RX3Q6EM1HAH8J8SZ6K3S9V job_op=*gen.Job_Build @module=waypoint.runner.app.example-nodejs-k8s.build err="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" timestamp=2021-06-21T23:44:35.372-0400
```

What seems to be happening here is that [client.IsErrConnectionFailed in fallback.go](client.IsErrConnectionFailed) isn't working. This looks like a bug in docker.

If i'm reading `go mod graph` right, we're using `github.com/docker/docker@v1.4.2-0.20190924003213-a8608b5b67c7`, which ultimately comes from `github.com/buildpacks/pack@v0.18.1`.

Docker a8608b5b67c7 has a bug, where the client returns an `errUnknown` wrapping an `errConnectionFailed`, but `errUnknown` did not implement `Unwrap`, and so cannot be inspected by `errors.As`: https://github.com/moby/moby/issues/41666. It was fixed here: https://github.com/moby/moby/pull/41667

Explicitly adding a newer version of docker/docker as a dependency fixes this.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.4.0
* Waypoint Server Platform and Version: v0.4.0
* Waypoint Plugin: docker

**Additional context**

### PR DESCRIPTION
**Pull request by izaaklauer**
Fixes #1684.

It's a bit of a mystery to me why running `go get github.com/docker/docker; go mod tidy` resulted in this many dependency changes, including a bbolt upgrade.

### CODE REVIEW

**Review by mitchellh — COMMENTED** [review]
Looks good, I'd tag this for backport.

**Review by krantzinator — APPROVED** [review]
So did we downgrade docker at some point and get the issue? Or was the issue introduced in one upgrade of docker and then resolved again in a subsequent upgrade of docker?
Fun fun.

**Comment by evanphx** [comment]
I think the previous upgrade of docker introduce the issue, and then this upgrade fixes it. Any idea which change fixes it?

**Comment by izaaklauer** [comment]
> I think the previous upgrade of docker introduce the issue, and then this upgrade fixes it. Any idea which change fixes it?

This is what fixes it: https://github.com/moby/moby/pull/41667

I actually found and made that fix myself locally, and then was disappointed when I rushed to make the docker PR and realized we were behind and someone had beaten me to it.

**Pull request merged**
