### PR TITLE
Begin to swap out custom WP IconTile for HDS IconTile

### PR DESCRIPTION
**Pull request by amyrlam**
- Add @hashicorp/design-system-components
- Swapped out IconTile in app, but not in /onboarding yet (could set up Percy there first? @sabrinako had proposed just a FlightIcon there instead of IconTile)

Extracted from: https://github.com/hashicorp/waypoint/pull/3288 (note: @sabrinako I noticed I could not co-commit with you https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors because of the extra settings on this repo, if there is another way just let me know!)

IS:
image

image

This view does not have Percy set up yet, probably because needs advanced stubbing, but IconTile is the same as the other pages (from above IS screenshots), which have Percy
image

### CODE REVIEW

**Comment by amyrlam** [comment]
(Rebased to fix my Verified commits)

**Comment by jgwhite** [comment]
> could set up Percy there first?

I think this PR could be a good moment to add Percy for the onboarding pages 👍

**Review by gregone — APPROVED** [review]
✨  Looks great!

**Comment by amyrlam** [comment]
@jgwhite @gregone I'm going to work on the side, when spare time. I think it could be good to get this merged and the next step from https://github.com/hashicorp/waypoint/pull/3288#issuecomment-1110436753 `Swap out IconTile in /onboarding for FlightIcon, add Percy, retire custom IconTile` can be a separate PR, as isn't a swap out, but more of a "redesign".

Wanted to check if you're cool with that? If so, can you +1 the Percy as the reviewer? If not, I can convert this to a draft, and un-draft it when add the second part

**Comment by jgwhite** [comment]
> I think it could be good to get this merged and the next step from https://github.com/hashicorp/waypoint/pull/3288#issuecomment-1110436753 `Swap out IconTile in /onboarding for FlightIcon, add Percy, retire custom IconTile` can be a separate PR, as isn't a swap out, but more of a "redesign".

Seems like a good plan to me. For visibility, could you extract that checklist into a quest issue (or something like that)?

> Wanted to check if you're cool with that? If so, can you +1 the Percy as the reviewer? If not, I can convert this to a draft, and un-draft it when add the second part 

+1’d

**Comment by amyrlam** [comment]
@jgwhite thanks, I tend to leave the Percy to the reviewer, is that the standard on Waypoint? Realize there isn't a way to force that AFAIK

Made this QUEST issue: https://github.com/hashicorp/waypoint/issues/3313 and will merge this in

**Comment by jgwhite** [comment]
> I tend to leave the Percy to the reviewer, is that the standard on Waypoint? Realize there isn't a way to force that AFAIK

We don’t have any particular policy right now. I tend to agree, that the reviewer’s “fresh eyes” are more likely to spot hairs out of place in Percy.

> Made this QUEST issue: #3313 and will merge this in

Very cool 👍

**Pull request merged**
