### PR TITLE
Fix `make gen/plugins`

### PR DESCRIPTION
**Pull request by krantzinator**
Option 2 of 2 to fix our plugin generation (option 1 is PR #3365):

Installing `protoc-gen-go` via `go install google.golang.org/protobuf/cmd/protoc-gen-go` results in the following errors when running `make gen/plugins`:
```
See https://grpc.io/docs/languages/go/quickstart/#regenerate-grpc-code for more information.
builtin/k8s/k8s.go:8: running "protoc": exit status 1
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC
```

This PR follows the suggested updates from the error message to enable us to continue generating our plugins.

### CODE REVIEW

**Review by briancain — COMMENTED** [review]
We could talk about this one in our next team sync. The option 1 feels like an easy temp fix for "today", where as this one feels like probably the right fix going forward should we choose to upgrade protoc soon.

**Comment by krantzinator** [comment]
Per discussion, I'll move the `go generate` stuff into its own `scripts/` location so that we don't have to update each plugin separately. Also see if the updates to `path=relative` lessen the requirement for endless `../`.

**Comment by denysvitali** [comment]
Any update here?
It's always painful to compile the `pb` files for this project :(

**Comment by briancain** [comment]
I think maybe we can close this now that #4444 is merged!

**Pull request closed without merging**
