### PR TITLE
Update Nomad ODR job to Batch Job

### LINKED ISSUE #3408: Nomad ODR causes excessive restarts
**Describe the bug**
Default nomad ODR config causes a huge amount of auto-restarts & log spam.  I have a constant stream of these:

```
2022-06-02T22:12:28.345-0700 [INFO]  client.alloc_runner.task_runner: restarting task: alloc_id=bda7add7-755c-7ea7-9c6f-fbf63c46eebf task=waypoint-task-01g4kzmmhmf03hzqrjpcbkfqxn reason="Restart within policy" delay=18.725400201s
```

Here's a sample alloc status with restart visible:

```
ID                  = bda7add7-755c-7ea7-9c6f-fbf63c46eebf
Eval ID             = 46b9ed66
Name                = waypoint-task-01g4kzmmhmf03hzqrjpcbkfqxn.waypoint-task-01g4kzmmhmf03hzqrjpcbkfqxn[0]
Node ID             = e4047e6b
Node Name           = nc-um350-1
Job ID              = waypoint-task-01g4kzmmhmf03hzqrjpcbkfqxn
Job Version         = 0
Client Status       = complete
Client Description  = All tasks have completed
Desired Status      = stop
Desired Description = alloc not needed due to job update
Created             = 16m29s ago
Modified            = 16m6s ago
Deployment ID       = b36c158b
Deployment Health   = healthy

Task "waypoint-task-01g4kzmmhmf03hzqrjpcbkfqxn" is "dead"
Task Resources
CPU        Memory          Disk     Addresses
0/200 MHz  17 MiB/600 MiB  300 MiB  

Task Events:
Started At     = 2022-06-03T05:12:29Z
Finished At    = 2022-06-03T05:12:33Z
Total Restarts = 1
Last Restart   = 2022-06-02T22:12:28-07:00

Recent Events:
Time                       Type        Description
2022-06-02T22:12:33-07:00  Killed      Task successfully killed
2022-06-02T22:12:33-07:00  Terminated  Exit Code: 2, Exit Message: "Docker container exited with non-zero exit code: 2"
2022-06-02T22:12:33-07:00  Killing     Sent interrupt. Waiting 5s before force killing
2022-06-02T22:12:29-07:00  Started     Task started by client
2022-06-02T22:12:28-07:00  Driver      Downloading image
2022-06-02T22:12:28-07:00  Restarting  Task restarting in 18.725400201s
2022-06-02T22:12:28-07:00  Terminated  Exit Code: 0
2022-06-02T22:12:12-07:00  Started     Task started by client
2022-06-02T22:12:10-07:00  Driver      Downloading image
2022-06-02T22:12:10-07:00  Task Setup  Building Task Directory
```

**Steps to Reproduce**
```
waypoint install -platform=nomad -accept-tos \
  -nomad-host=https://nomad.service.consul:4646 \
  -nomad-host-volume=waypoint-storage
```

Then configure project for git over HTTPS polling.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.8.2
* Waypoint Server Platform and Version: nomad 1.2.8
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

### PR DESCRIPTION
**Pull request by paladin-devops**
The Nomad job for the on-demand runner is converted to a batch job in this update.

Closes #3408.

### CODE REVIEW

**Review by krantzinator — APPROVED** [review]
Looks good. I was wondering if we should let some of the times be configurable, but then figured Waypoint should probably have opinions about operations at the level that `tasks` run at.

**Comment by evanphx** [comment]
@paladin-devops That looks totally good to me. I don't recall what `interval` controls, but the only thing I'd say is make sure that nomad allows the task to run for a long time.

**Review by demophoon — APPROVED** [review]

**Comment by briancain** [comment]
Before merge, we're going to make sure that if you run a long running batch job, things still operate as expected /cc @paladin-devops

**Pull request merged**
