### PR TITLE
serverinstall/k8s: Actually set on-demand runner image with Helm

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, Helm would never properly set the right on-demand runner image specified by the CLI install flags. This commit fixes that by ensuring those values are properly set with the Helm chart yaml prior to the install.

I don't know if this requires a changelog because the bug might of been introduced after the last release.

### CODE REVIEW

**Comment by briancain** [comment]
Note that this only fixes one part of https://github.com/hashicorp/waypoint/issues/3832, it fixes the ODR image being properly set but does not yet fix the double bootstrap issue. That will happen in a different PR.

**Comment by briancain** [comment]
With this fix now:
```
brian@ubuntu:waypoint-tetris λ waypoint runner profile list                                                                         ±[main]
Runner profiles
              NAME             | PLUGIN TYPE |             OCI URL             | TARGET RUNNER | DEFAULT
-------------------------------+-------------+---------------------------------+---------------+----------
  01GCEW5DRG12FS9KG70PRT14ZJ   | kubernetes  | localhost:5000/waypoint-odr:dev | *             | yes
  kubernetes-bootstrap-profile | kubernetes  | localhost:5000/waypoint-odr:dev | *             | yes

```

**Review by xiaolin-ninja — APPROVED** [review]
LGTM, can you also add in the install CLI command you used?

**Review by krantzinator — APPROVED** [review]

**Review by izaaklauer — COMMENTED** [review]
👍

**Pull request merged**
