### PR TITLE
docs: Fix typo for config source-set

### PR DESCRIPTION
**Pull request by backspace**
Maybe this was a problem introduced in #868?

### CODE REVIEW

**Comment by backspace** [comment]
ah I did see that the string existed in multiple places but I didn’t realise it needed to be run locally. I can try that later today 🤓

**Comment by briancain** [comment]
Sounds great @backspace ! The trick to making it work is you'll just need a little Waypoint server locally, it does some plugin doc generation there when you run `make docs/website-mdx`. You should be able to just install it to docker to make it work right.

**Comment by backspace** [comment]
Okay, I ran that locally and it changed three files. But there’s [another instance](https://github.com/hashicorp/waypoint/blob/main/website/content/partials/components/configsourcer-null.mdx) that didn’t change… should I change it manually? 😯

Also I clearly didn’t read `CONTRIBUTING.md` and used the Github UI to propose this change with the default branch name. I can close and reopen if that’s helpful!

**Comment by briancain** [comment]
@backspace - no worries, the branch name is fine!

I'm not sure why that one didn't update, strange. I'd say update it manually and that should be good. Thank you!

**Comment by backspace** [comment]
👍🏻 done now, thank you!

**Pull request merged**
