### PR TITLE
internal/cli: version shows Waypoint server version

### LINKED ISSUE #1323: Add a command to show the Waypoint server version
**Is your feature request related to a problem? Please describe.**
I wasn't able to figure out how to get my current Waypoint server version. I thought `waypoint version` or `waypoint server version` might do that but they don't.

**Describe the solution you'd like**
It would be great to make the `waypoint version` and `waypoint server version` commands to display the current Waypoint server version.

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #1323 

This augments `waypoint version` to show the server version when available. This fails gracefully if the connection fails or there is no Waypoint server available. This command uses an arbitrary 2 second timeout so it doesn't block for a very long time if the connection is not working or taking a long time (unlike the CLI for other operations which will wait much longer).

image

### CODE REVIEW

**Comment by krantzinator** [comment]
Did we want to include this on the `--version` flag also, or just on the command?

**Comment by mitchellh** [comment]
> Did we want to include this on the `--version` flag also, or just on the command?

Oh that does a different thing? Yes... yes... I'm gonna just fix that to call `version` so the behavior is the same.

**Comment by mitchellh** [comment]
Done

**Review by krantzinator — APPROVED** [review]
🚢

**Pull request merged**
