### PR TITLE
Track step groups more accurately

### PR DESCRIPTION
**Pull request by evanphx**
This goes along with https://github.com/hashicorp/waypoint-plugin-sdk/pull/31 to properly track concurrent step groups to avoid confusing UI issues.

### CODE REVIEW

**Comment by krantzinator** [comment]
Is this supposed to fix the problem with step groups exiting too quickly to log their final state, or be part 1 in the puzzle?
I just ran a `waypoint init` (installed server in nomad, waypoint-examples/nomad/nodejs) off this branch and got an unfinished state:
```
$ waypoint init
✓ Configuration file appears valid
✓ Connection to Waypoint server was successful
✓ Project "example-nodejs" and all apps are registered with the server.
⠹ Validating required plugins...
$
```

**Comment by krantzinator** [comment]
Ah maybe I should wait on this until the sdk PRs are merged in 😄

**Review by briancain — COMMENTED** [review]
It looks like the sdk fixes are in and I have the same issue with `waypoint int`

wpinit

And then the `waypoint up` output is completely lost 🤔 

Screenshot from 2021-05-19 11-34-03

Or trying a second time:

wpup

**Comment by krantzinator** [comment]
@evanphx Should we move this to 0.5 milestone?

**Comment by xiaolin-ninja** [comment]
@evanphx please magnificent sir amongst sirs, will we carry this wonderful PR to its completion at a date in the near future befitting of your sirness? <3

**Comment by evanphx** [comment]
@xiaolin-ninja A chance to debug, perchance to find this bug most foul! Forthwith, I shall turn the hourglass once again and bring the powers that be upon it!

**Comment by briancain** [comment]
Should we close this?

**Pull request closed without merging**
