### PR TITLE
Add ctx to some serverstate app ops

### PR DESCRIPTION
**Pull request by cicoyle**
I'm phasing this out. There will be more to come. 

Ctx is added to the following funcs:
- Artifact
- Build
- Task
- Pipeline
- PipelineRun

### CODE REVIEW

**Comment by jgwhite** [comment]
@cicoyle am I right in thinking we need to hold off updating the version of waypoint core we use until this work is complete?

**Comment by cicoyle** [comment]
> @cicoyle am I right in thinking we need to hold off updating the version of waypoint core we use until this work is complete?

Hey @jgwhite, did I accidentally update the version somewhere? I am adding the ctx to all serverState interface functions, such that if we have an expensive query later on, we may cancel the query. I didn't think I updated the version of waypoint here, but I may have missed it.

**Comment by jgwhite** [comment]
@cicoyle sorry, I think my sentence was a little ambiguous! I didn’t meant to imply that you had updated the version of Waypoint core. Rather, I meant: should other folks working on cloud-waypoint-service hold off updating the version of Waypoint core?

The reason I ask is because I wanted to run https://github.com/hashicorp/waypoint/pull/4082 against cloud-waypoint-service but found the project wouldn’t compile due to missing context arguments. So I assumed I should hold off until your work here is complete.

**Comment by jgwhite** [comment]
@cicoyle you know what — I know why my last comment was confusing — I left it against the wrong PR 😅 

Don’t worry about my question — I didn’t mean to imply that you had updated anything inadvertently — I was just asking how to synchronize myself around this change.

**Review by evanphx — APPROVED** [review]

**Pull request merged**
