### PR TITLE
Update alert banner for HashiConf Global 2021

### PR DESCRIPTION
**Pull request by EnMod**
[:mag: Preview link upcoming](https://waypoint-git-nqupdate-alert-banner-hcg2021-hashicorp.vercel.app/)

---

This PR updates the alert banner for HashiConf Global 2021.

### CODE REVIEW

**Review by mwickett — APPROVED** [review]

**Comment by EnMod** [comment]
@mwickett I'm thinking I can ignore the failed `website-mdx` check here?

**Comment by mwickett** [comment]
@EnMod I'm unsure actually. Probably worth a check with @BRKalow (ping!)

**Comment by BRKalow** [comment]
@EnMod Could you run `npx next-hashicorp format`? Looks like the `alert-banner` file is failing the prettier check there.

**Comment by EnMod** [comment]
@BRKalow Pushed! That seems to have done it.

**Review by BrandonRomano — APPROVED** [review]

**Comment by krantzinator** [comment]
Does this mean we can close #2011 in favor of this PR?

**Comment by EnMod** [comment]
@krantzinator Yes that makes sense; the info in this PR is the most up-to-date 👍

**Comment by briancain** [comment]
HashiConf has come and gone....should this be closed? @EnMod

**Comment by EnMod** [comment]
Ah yes, good point @briancain ! The changes seem to have gone in via #2509. Closing!

**Comment by briancain** [comment]
Thank you! ❤️

**Pull request closed without merging**
