### PR TITLE
Add command to stop Waypoint server in Docker

### PR DESCRIPTION
**Pull request by dominikbraun**
Addresses #479. 

This PR is an attempt to implement a command for stopping a Waypoint server running in Docker and basically uninstalling it. As proposed in [this comment](https://github.com/hashicorp/waypoint/issues/479#issuecomment-710738422), the command name is `waypoint server docker stop`.

The current workflow looks as follows:
1. Look for a running Waypoint container.
2. Shut it down gracefully.
3. Remove the container.
4. Check whether the `waypoint-server` volume exists, which should be the case.
5. If it does, remove it as well.

Two things came to my mind:
* Would it make sense to offer a CLI flag to preserve the volume?
* Strictly speaking, this command isn't the inverse operation of `server run` but of `server install` instead. May `server docker uninstall` be an appropriate alternative command name?

I'm happy to hear your opinions and ideas on this.

### CODE REVIEW

**Comment by mitchellh** [comment]
So one thing is we’re currently planning on introducing `server uninstall` capabilities for all platforms in Waypoint 0.2. We just started planning this work today. So I’m wondering if we should just hold off on this... sorry! Your contribution is super welcome here but not sure if we want to merge this then undo it or move it quickly for 0.2

**Comment by dominikbraun** [comment]
Merging and un-doing this would probably be of little value for the product. This is merely a draft - feel free to close it or proceed with it as you wish.

**Comment by mitchellh** [comment]
Roger, we’ll discuss it. Sorry to not warn you or update the issue earlier this literally came out during discussions like 5 or 6 hours ago.

**Comment by mitchellh** [comment]
Yeah we're gonna close this. Sorry! But we'll have a solution soon.

**Pull request closed without merging**
