### PR TITLE
feat(ui): show deployment URL if available

### PR DESCRIPTION
**Pull request by denysvitali**
UI Changes related to #1387

This PR only contains the UI changes to ease the frontend review. This change basically makes the deployment URL visible and removes the "Visit Deployment" title to be consistent with the Release URL button:

image

In addition to this, a consistency change was performed (Deployments were displayed in the form `#1` instead of `v1` when you visited the deployment page)

### CODE REVIEW

**Comment by denysvitali** [comment]
Ping @hashicorp/waypoint-frontend

**Comment by gregone** [comment]
@denysvitali Thank you for the PR! 

As mentioned in #1387, this is a great idea. The implementation is good and just needs a few tweaks, as detailed below, and in code comments:

First of all, we're about to merge https://github.com/hashicorp/waypoint/pull/1713 which also addresses the consistency issue between `vX` and `#X` labels, but is probably going to create some conflicts with your PR. We'll need to rebase to include those changes. 

Did you update the files in `ui/lib` by running the `make gen/ts` task? (as described in the [UI Readme](https://github.com/hashicorp/waypoint/tree/main/ui#generating-type-definitions-after-making-api-changes)). If you didn't, those changes will be overwritten the next time we generate those.

I appreciate the use of the full URL and the consistency with the release URL 👍

**Comment by denysvitali** [comment]
> Did you update the files in ui/lib by running the make gen/ts task? (as described in the UI Readme). If you didn't, those changes will be overwritten the next time we generate those.

Done, the biggest issue is that I had to include in this PR also the server.proto, which in turn shows a change of server.pb.go and finally this allows the UI to have the correct Protobuf-generated TS 👍

**Comment by gregone** [comment]
@denysvitali Thank you! This is looking great. Let's wait until https://github.com/hashicorp/waypoint/pull/1713 is merged, then after you get approval on https://github.com/hashicorp/waypoint/pull/1387, I'll approve and we can merge this one along with the server stuff

**Comment by gregone** [comment]
@denysvitali  #1713 has been merged. Can you rebase (and re-run `make gen/ts`) or would you like me to assist?

**Comment by denysvitali** [comment]
I'll be more than happy if you can do it yourself since the sooner I'll be able to do it would be tomorrow morning 😁

**Review by gregone — APPROVED** [review]
Thank you @krantzinator for dealing with the rebase. 

Tested everything locally, works great! Thanks for the contribution @denysvitali !

**Comment by denysvitali** [comment]
Thank you all! <3

**Pull request merged**
