### PR TITLE
UI tests in ci

### LINKED ISSUE #1541: Run Frontend Tests in CI
With the A11y warnings now clean, we should look into [re-enabling the Ember tests in CircleCI](https://github.com/hashicorp/waypoint/blob/main/.circleci/config.yml#L379-L410)

### PR DESCRIPTION
**Pull request by gregone**
Fixes #1541

Updates the CircleCI Config to re-add the ember frontend tests. 
In [this commit](https://github.com/hashicorp/waypoint/pull/1619/commits/6810a2ac1b392d9008f86ffb53dfa267dbec912f#diff-ae40626f5637e397ca4fe0447a37c3881ea70449c4d670bb2d0cdafb9180bafcR15) you'll notice I excluded `iframe` from a11y testing as the QUnit wrapper iframe was throwing a warning. This should be fine for now (until we decide to support embedding GeoCities content inside the Waypoint app 😂)

### CODE REVIEW

**Comment by jgwhite** [comment]
> until we decide to support embedding GeoCities content inside the Waypoint app

definitely the tentpole feature of 0.7.0 😅

**Review by jgwhite — APPROVED** [review]
Looks great and seems like the frontend tests take a similar amount of time to the go tests 👍

**Comment by krantzinator** [comment]
> > until we decide to support embedding GeoCities content inside the Waypoint app
> 
> definitely the tentpole feature of 0.7.0 sweat_smile

OMG 🤣 🤣 
The nostalgia would probably be a draw 😂

**Review by krantzinator — APPROVED** [review]
🚀

**Pull request merged**
