### PR TITLE
proto: update protobufs to latest versions

### PR DESCRIPTION
**Pull request by krantzinator**
I noticed we were running generations with a different version than in the go.mod so this is an attempt to sync everything up.

### CODE REVIEW

**Comment by mitchellh** [comment]
With this PR, `make gen/server` results in this change for me. Is this what you see too?

image

**Comment by krantzinator** [comment]
@mitchellh Ah, I separately updated my `protoc` version to match the most-recently used version for generations. Is that managed in nix also?

**Comment by mitchellh** [comment]
> @mitchellh Ah, I separately updated my `protoc` version to match the most-recently used version for generations. Is that managed in nix also? (So I'm running `protoc 3.15.8` locally)

Literally everything is managed by Nix ;) I pin my entire env. Let me do some research to get 3.15.8 in there.

**Comment by mitchellh** [comment]
I pinned protoc to 3.15.8 for me.

**Comment by krantzinator** [comment]
> I pinned protoc to 3.15.8 for me.

Beautiful, thanks

**Review by briancain — APPROVED** [review]

**Pull request merged**
