### PR TITLE
ui: display status reports on deployments

### LINKED ISSUE #1237: Status from health checks in UI
#### Is your feature request related to a problem? Please describe.

As we add health checks for deployments and releases (https://github.com/hashicorp/waypoint/issues/1224), we need to display those in the UI.  

#### Describe the solution you'd like

A green check/red cross icon displayed alongside build and deployments , with a link to the build/release output for quick inspection.

### PR DESCRIPTION
**Pull request by jgwhite**
## What is this?

Fixes #1237 

This PR adds badges to deployments indicating the result of Waypoint’s latest status report (aka health check).

## What’s the plan?

- [x] Create `<StatusBadge>`
- [x] Add Mirage layer
- [x] Load status reports
- [x] Display status report badge on deployment list view (where available)
- [x] Display status report badge on deployment detail view (where available)
- [x] Add test coverage
- [x] Add changelog entry

## What are we saving for a future PR/release?

- Fix icon alignment in Safari (#1586)
- Make the “starting…” icon pulse (steal tailwind pulse CSS) (#1587)
- Fix awkward wrapping of tooltips, maybe align center (#1588)
- Display status report on releases
- Use `<StatusBadge>` everywhere in place of the existing success/failure badges (#1581)

## What does it look like?

image

image

### Using Mirage

1. Check out the branch:
   ```sh
   git checkout ui-health-checks-integration
   ```
2. Boot the dev server
   ```sh
   cd ui && ember serve
   ```
3. [Visit the demo deployment list view](http://localhost:4200/default/marketing-public/app/wp-matrix/deployments)
4. Verify you see status badges
5. [Visit the demo deployment detail view](http://localhost:4200/default/marketing-public/app/wp-matrix/deployment/R7X1PI460E031I83UAJ8JYUA)
6. Verify you see a status badge

### For realsies

1. Check out the branch:
   ```sh
   git checkout ui-health-checks-integration
   ```
2. Build the ember app
   ```sh
   (cd ui && make)
   ```
3. Bundle the static assets
   ```sh
   make static-assets
   ```
4. Build the dev server
   ```sh
   make docker/server
   ```
5. Build the CLI
   ```sh
   make bin
   ```
6. Install waypoint on your platform of choice, i.e.
   ```sh
   ./waypoint install -platform=kubernetes -accept-tos -k8s-server-image=waypoint:dev
   ```
7. Open the UI
   ```
   ./waypoint ui -authenticate
   ```
8. Try out an example app of your choice (i.e. [kubernetes/nodejs](https://github.com/hashicorp/waypoint-examples/tree/main/kubernetes/nodejs))
9. Verify you see status badges

### CODE REVIEW

**Review by briancain — COMMENTED** [review]
Will give a proper review tomorrow since you mention you have a few more TODOs, but gave this a shot locally as is stands right now and looks good to me! 🎉

**Review by krantzinator — APPROVED** [review]
Looking great!

**Review by izaaklauer — APPROVED** [review]
Tested success scenarios locally, and it looks great! Failure scenarios are very hard to produce locally at this point - you need to get the deployment into a bad state in the time between the deployment completing and the first status check kicking off. Will be easier once we have polling.

**Review by briancain — APPROVED** [review]
Nice job!! Looks great ❇️ ✔️

**Pull request merged**
