### PR TITLE
ui: ember 3.28

### PR DESCRIPTION
**Pull request by jgwhite**
## Why the change?

Ember 3.28 is now an LTS release. We don’t necessarily have to upgrade now, but I needed a distraction from something more challenging and thought it’d be useful to know the following:

- Is anything stopping us upgrading?
- How many deprecations do we have to attend to?

Note that this re-uses work from #2738 which will unfortunately have the same issue of confusing ember-asset-size-action.

## What’s the plan?

- [x] Upgrade everything that needs upgraded ([official guide here](https://blog.emberjs.com/ember-4-0-released#toc_how-to-upgrade-your-project-to-ember-4))
- [x] Decide what to do about ember-asset-sizes

## How do I test it?

1. `git checkout ui/ember-3.28`
2. [Boot the dev server](https://github.com/hashicorp/waypoint/blob/main/ui/README.md#running--development)
3. Smoke test
4. Verify nothing obvious is broken

### CODE REVIEW

**Comment by gregone** [comment]
I think we can get rid of asset-size and work on a better solution later

**Comment by sabrinako** [comment]
Screen Shot 2022-01-19 at 3 21 31 PM
Not sure if this is a me issue or the PR code?

**Comment by jgwhite** [comment]
@sabrinako curious! I don’t see any reference to `levenary` in our `yarn.lock`. Could you try `rm -rf node_modules && yarn install`? I’m not really sure what’s going on, but it doesn’t seem to be affecting CI so I suspect it’s something stray package in your local `node_modules`.

**Comment by sabrinako** [comment]
@jgwhite yeah I thought it was weird, I didn't recognize the package but was wondering if it was a dependency somewhere down the line. When I switched branches the issue didn't persist so I wasn't sure if it was branch-related but after running the command you listed + trying a more thorough from-scratch boot, everything looks good 👍

**Review by sabrinako — APPROVED** [review]
LGTM! Sorry for the confusion earlier with the strange error message 😅

**Comment by jgwhite** [comment]
Thanks @sabrinako. I’ll wait for @gregone to take a look at this too before we merge.

**Review by gregone — APPROVED** [review]

**Pull request merged**
