### PR TITLE
Add ability to pass josbpec path parameter to nomad plugin

### PR DESCRIPTION
**Pull request by rkrasiuk**
Addresses #516 

I had multiple questions which I thought better to discuss with maintainers rather than deciding on my own

* Should the application throw on other parameters provided together with `jobspec`?
* Should any other meta tags be set on the job that are specific to how waypoint manages the deployments? 

And, in general, any other comments appreciated.

### CODE REVIEW

**Comment by mitchellh** [comment]
Thank you for taking a stab at this! I think there are some open questions I’d love to discuss both here and internally about this. Before that, I want to say that we 100% want to support a job spec oriented plugin. That is not in question.

The question is whether this fits in the existing `use “nomad”` plugin or if we should make a separate plugin. Or, if this should support some templating so we can get the Docker image created into it for example.

Its the weekend so I just wanted to drop this by but I’ll think about this and bring it up with the team Monday.

**Comment by rkrasiuk** [comment]
@mitchellh sure! thanks for a quick weekend response. i'd love `waypoint` to eventually support `levant` as well and, with that said, separate plugin, smth like `use "nomad-template"`, sounds more logical. just tell me what you decide and how i can help ; -)

**Comment by evanphx** [comment]
Hi @rkrasiuk, thanks again for the PR! We're solving this problem a different way and it should be available in 0.4.0.

**Comment by rkrasiuk** [comment]
@evanphx excited to see the solution. thanks for the update!

**Comment by mitchellh** [comment]
I'll keep this open for now since the PR isn't quite merged, but here is the PR to watch: https://github.com/hashicorp/waypoint/pull/1299

**Comment by mitchellh** [comment]
Oh this is a PR. Brain confusion. Anyways, that link to the PR is right. I will close this haha

**Pull request closed without merging**
